title = 'LMS Docs'
description = 'Learn to manage your server with LMS Discord Bot'
images = ['images/feature.png']
metaThemeColor = "#2e9eef"
enableCopyright = true

BookTheme = 'dark'
BookLogo = 'logo.png'


[search]
on = false

[author]
name = "LMS Developer Team"
