title = 'LMS Docs'
description = 'Learn to manage your server with LMS Discord Bot'
images = ['images/feature.png']
metaThemeColor = "#2e9eef"
enableCopyright = true

[logo]
darkMode = 'favicons/favicon-48x48.png'
lightMode = 'favicons/favicon-48x48.png'

[search]
on = true
global = true

[author]
name = "LMS Developer Team"
